"""initial schema

Revision ID: b5fcfa402021
Revises: 
Create Date: 2026-04-26 21:54:20.189141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5fcfa402021'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fdid', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apparatus',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('unit_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('service_status', sa.String(length=32), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'local_id', name='uq_apparatus_dept_local')
    )
    op.create_table('checklist_templates',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('badge_number', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_table('checklist_completions',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('apparatus_id', sa.UUID(), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['apparatus_id'], ['apparatus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'local_id', name='uq_checklist_completions_dept_local')
    )
    op.create_table('incidents',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('incident_number', sa.String(length=64), nullable=True),
    sa.Column('incident_type', sa.String(length=64), nullable=True),
    sa.Column('location_address', sa.String(length=512), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('alarm_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('on_scene_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'local_id', name='uq_incidents_dept_local')
    )
    op.create_index('ix_incidents_dept_alarm', 'incidents', ['department_id', 'alarm_time'], unique=False)
    op.create_table('ppe_items',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('last_inspection', sa.Date(), nullable=True),
    sa.Column('retired_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'local_id', name='uq_ppe_items_dept_local')
    )
    op.create_table('scba_units',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('cylinder_hydro_date', sa.Date(), nullable=True),
    sa.Column('regulator_service_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'local_id', name='uq_scba_units_dept_local')
    )
    op.create_table('sync_records',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('vector_clock', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_records_dept_updated', 'sync_records', ['department_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_sync_records_local_id'), 'sync_records', ['local_id'], unique=False)
    op.create_index('ix_sync_records_table_record', 'sync_records', ['table_name', 'record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_records_table_record', table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_local_id'), table_name='sync_records')
    op.drop_index('ix_sync_records_dept_updated', table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_table('scba_units')
    op.drop_table('ppe_items')
    op.drop_index('ix_incidents_dept_alarm', table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('checklist_completions')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('checklist_templates')
    op.drop_table('apparatus')
    op.drop_table('departments')
    # ### end Alembic commands ###
